steps:
  - name: 'gcr.io/cloud-builders/git'
    args:
      - "submodule"
      - "update"
      - "--init"
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - "build"
      - "--file=docker-stellar-core/Dockerfile"
      - "--tag=us.gcr.io/$PROJECT_ID/stellar-core:staging-latest"
      - "--tag=us.gcr.io/$PROJECT_ID/stellar-core:$REVISION_ID"
      - "docker-stellar-core"
images:
  - 'us.gcr.io/$PROJECT_ID/stellar-core'
timeout: 3600s
